from MiniRedis import Redis
import time

def main():
    miniRedis = Redis.Redis(4)
    
    print("---set---")
    status = miniRedis.set("teste2", 2)
    print(status)
    status = miniRedis.set("teste2", 22)
    print(status)
    status = miniRedis.set("teste6", 16)
    print(status)
    status = miniRedis.set("teste10", 4)
    print(status)
    status = miniRedis.set("teste14", 14)
    print(status)

    print("---set-ex---")
    status = miniRedis.set("teste0", 2, "EX", 2)
    print(status)
    status = miniRedis.set("teste01", 22, "EX", 4)
    print(status)
    status = miniRedis.set("teste02", 16, "EX", 8)
    print(status)

    time.sleep(10)

    print("---get---")
    value = miniRedis.get("teste2")
    print(value)
    value = miniRedis.get("teste6")
    print(value)
    value = miniRedis.get("teste10")
    print(value)
    value = miniRedis.get("teste14")
    print(value)

    print("---delete---")
    removed = miniRedis.delete("teste14")
    print(removed)
    value = miniRedis.get("teste14")
    print(value)
    removed = miniRedis.delete("teste6")
    print(removed)

    print("---dbsize---")
    size = miniRedis.dbsize()
    print(size)

    print("---incr---")
    newValue = miniRedis.incr("teste10")
    print(newValue)
    newValue = miniRedis.incr("teste10")
    print(newValue)
    newValue = miniRedis.incr("teste10")
    print(newValue)
    newValue = miniRedis.incr("teste10")
    print(newValue)
    newValue = miniRedis.incr("teste10")
    print(newValue)
    removed = miniRedis.delete("teste10")
    print(removed)
    newValue = miniRedis.incr("teste10")
    print(newValue)

    print("---zadd---")
    zinsert = miniRedis.zadd("zset1", "-inf", "mil")
    print(zinsert)
    zinsert = miniRedis.zadd("zset1", 900, "mil")
    print(zinsert)
    zinsert = miniRedis.zadd("teste10", "900", "mil")
    print(zinsert)
    zinsert = miniRedis.zadd("zset2", "700", "amil")
    print(zinsert)
    zinsert = miniRedis.zadd("zset2", "1000", "amil")
    print(zinsert)
    zinsert = miniRedis.zadd("zset2", "2000", "odoismil")
    print(zinsert)
    zinsert = miniRedis.zadd("zset2", "3000", "ctresmil")
    print(zinsert)
    zinsert = miniRedis.zadd("zset2", "4000", "dquatromil")
    print(zinsert)
    zinsert = miniRedis.zadd("zset2", "5000", "ecincomil")
    print(zinsert)
    zinsert = miniRedis.zadd("zset2", "6000", "fseismil")
    print(zinsert)
    
    print("---zcard---")
    zcard = miniRedis.zcard("zset2")
    print(zcard)
    zcard = miniRedis.zcard("zset1")
    print(zcard)
    zcard = miniRedis.zcard("zsetX")
    print(zcard)

    print("---zrank---")
    zrank = miniRedis.zrank("teste10", "mil")
    print(zrank)
    zrank = miniRedis.zrank("zset2", "amil")
    print(zrank)
    zrank = miniRedis.zrank("zset2", "odoismil")
    print(zrank)
    zrank = miniRedis.zrank("zset2", "ctresmil")
    print(zrank)

    print("---zrange---")
    zrange = miniRedis.zrange("zset2", 0, 3)
    print(zrange)

    val = miniRedis.get("zset2")
    print(val)

if __name__== "__main__":
    main()

